print("List of installed systen commands (6)")
print("Commands - full list of commands")
print("Clean - Cleans your system for you")
print("update - updater")
print("exit - exits custom shell")
print("reboot - Reboots your system")
print("shutdown - Shut your system down")